export const EVENT_1 = {
  id: 343491,
  title: 'Open Air Poetry Reading and Discussion',
  start: '2021-04-21',
  end: '2021-04-27',
  allDay: 1,
  image: 'https://static.wixstatic.com/media/11062b_b31efefcdf3846849b7fe93d9203f105~mv2_d_6200_4132_s_4_2.jpg',
  desc: '<p>Four amazing evenings of poetry reading and discussion! We will do a poetry reading from various poets followed by an interactive discussion. Each day there will be three poets whose works will be read and discussed.<br>If you want to attend and listen to some great poetry, please register. Our organizers will get back to you.</p>',
  color: 'red',
  venue: {
    name: 'Virginia Road',
    address: '1485 Virginia Road, San Marino, CA 91108, USA',
    city: '',
    statesList: '',
    country: '',
    postal: '',
    phone: '',
    email: '',
    website: '',
    lat: 34.1204167,
    long: -118.1201348,
  },
  organizer: { name: '', phone: '', website: '', email: '' },
  repeat: { type: '', interval: '', end: '', advanced: '', exclude: '' },
  kind: '4',
  categories: [],
  guests: [],
  registration: null,
  tickets: null,
};
export const EVENT_2 = {
  id: 782910,
  title: 'Bisong Art Gallery',
  start: '2022-02-04T18:00',
  end: '2022-02-04T21:00',
  allDay: 0,
  image: '',
  desc: '<p>Bisong Art Gallery along with The D.R.E.A.M Affect Foundation is partnering with Prairie View A&amp;M Northwest Houston Center for a Black History Month Exhibition.</p><br><p>"Culture: Our New Normal" draws attention to the current events of black culture and how they continue to shape history. A portion of the proceeds will go to a scholarship fund for a Fine Art Student at PVAMU.</p>',
  color: '#9fe1e7',
  venue: {
    address:
      'Prairie View A&M University, N.W. Houston Center, 9449 Grant Road, Houston, TX 77070, USA',
    email: 'navasardianmichael@gmail.com',
    name: 'Prairie View A&M University',
    phone: '+7 988 176-15-99',
    website: 'https://www.youtube.com/watch?v=VaVH2SyxKOY',
    lat: 29.9658645,
    long: -95.5587025,
  },
  organizer: {
    email: 'info@bisonggallery.com',
    name: 'Bisong Art Gallery',
    phone: '713-498-3015',
    website: 'www.bisonggallery.com',
  },
  repeat: { type: '', interval: '', end: '', advanced: '' },
  kind: '1',
  categories: [{ id: 19412, name: 'Opening Reception', color: 'deepskyblue' }],
  guests: [],
  registration: null,
  tickets: null,
};

export const CUSTOM_CLASSNAMES = [
  'custom-class-name-1'
]